# Generated by Django 5.2.2 on 2025-07-29 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firebase_auth', '0005_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_available_now', models.BooleanField(default=False)),
                ('ad_type', models.CharField(choices=[('videographer', 'Videographer'), ('photographer', 'Photographer'), ('snowRemoval', 'Snow Removal'), ('automotive', 'Automotive'), ('moving', 'Moving'), ('websiteDesign', 'Website Design')])),
                ('is_active', models.BooleanField(default=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='ads/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='ads/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='ads/photos/')),
                ('location', models.CharField(blank=True, help_text='City / General Area', max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags like: wedding (for photography), blog (for website)', max_length=200)),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills like: Photoshop, Django, etc.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='firebase_auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='ads_ad_title_ce8d95_idx'), models.Index(fields=['tags'], name='ads_ad_tags_350c5b_idx'), models.Index(fields=['location'], name='ads_ad_locatio_489732_idx'), models.Index(fields=['ad_type'], name='ads_ad_ad_type_9999b3_idx'), models.Index(fields=['is_available_now'], name='ads_ad_is_avai_8a192a_idx')],
            },
        ),
    ]
