# Generated by Django 5.2.2 on 2025-07-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
