# Generated by Django 5.2.2 on 2025-09-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='photo_3',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.ad')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
