# Generated by Django 5.2.2 on 2025-08-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_photo_1_alter_ad_photo_2_alter_ad_photo_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='ad_type',
            field=models.CharField(choices=[('MECHANIC', 'Mechanic'), ('OTHER', 'Other')]),
        ),
    ]
