# Generated by Django 5.2.2 on 2025-08-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cost',
            field=models.CharField(default='0/hr', max_length=200),
            preserve_default=False,
        ),
    ]
