# Generated by Django 5.2.2 on 2025-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='1', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
