# Generated by Django 5.2.2 on 2025-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0002_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='null', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
