# Generated by Django 5.2.2 on 2025-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase_auth', '0004_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
